# Site settings
title: Unni S Mohan  
name: Unni S Mohan


#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/unni-s-mohan/

#Any buzzword skills you want to include
skills:
 - Linux
 - Mysql
 - Python
 - Bash Shell Scripting
 - Diameter
 - SS7
 - Jmeter
 - Business Analysis
 - Technical Architecture
#Work experience is required
roles:
 - title: Senior Implementation Engineer
   start: 2012
   end: Ongoing
   employer: 6D Technologies
   description: Design, Testing and Delivery of Telecom OSS/BSS and VAS solutions.

#Education is required
education:
 - level: Btech
   date: 2008
   subject: Electronics and Communication
   school: College Of Engineering Poonjar 
intro: |
 Experienced Senior Implementation Engineer with a demonstrated history of working in the telecommunications industry. Skilled in BSS, CRM, Off line billing, OCS, CAMEL, PCRF,SMSC, MMSC,Linux and Python. Strong  professional with  8+ years of experience in Project Management, Business Analysis, Migration Solution Analysis, Integration testing, Functionality testing and Service delivery.
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Linux</strong>: My current role uses Linux as the primary os
